# Generated by Django 4.2.2 on 2023-06-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coverpage', models.ImageField(blank=True, null=True, upload_to='')),
                ('authorname', models.CharField(max_length=200)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('total_pages', models.IntegerField(blank=True, null=True)),
                ('phone_no', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(max_length=200)),
                ('adress', models.CharField(max_length=200)),
            ],
        ),
    ]
